# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IavOmni9DqyrZeatDn19HL55wDYsTzNU
"""

from flask import Flask, request, jsonify
import requests
import base64
import os
import cv2
import numpy as np

app = Flask(__name__)
# Разрешаем грузить файлы до 100 МБ
app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024

ROBOFLOW_API_KEY = "zipFoxXwSowFhMRI79Sv"
PROJECT_NAME = "candidates-chess"
VERSION = "2"

@app.route('/')
def home():
    return '''
    <style>
        body { font-family: sans-serif; text-align: center; padding-top: 50px; background: #f0f2f5; }
        .box { background: white; display: inline-block; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        button { background: #007bff; color: white; border: none; padding: 12px 24px; cursor: pointer; border-radius: 5px; font-size: 16px; font-weight: bold;}
    </style>
    <div class="box">
        <h1>CogniMetrics AI: Visual Demo</h1>
        <p>Upload a chess image or video to see the DeepFocus bounding boxes.</p>
        <form action="/classify" method="post" enctype="multipart/form-data">
            <input type="file" name="file" required><br><br>
            <button type="submit">Analyze & Visualize</button>
        </form>
    </div>
    '''

@app.route("/classify", methods=['POST'])
def classify():
    if 'file' not in request.files:
        return "No file uploaded", 400

    file = request.files['file']
    filename = file.filename.lower()

    try:
        file_bytes = np.frombuffer(file.read(), np.uint8)

        # Если видео - берем 1 кадр
        if filename.endswith(('.mp4', '.avi', '.mov', '.mkv')):
            temp_path = "temp_video.mp4"
            with open(temp_path, 'wb') as f:
                f.write(file_bytes)
            cap = cv2.VideoCapture(temp_path)
            success, frame = cap.read()
            cap.release()
            if os.path.exists(temp_path):
                os.remove(temp_path)
            if not success:
                return "Could not extract frame", 500
            img = frame
        else:
            img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

        height, width = img.shape[:2]
        if width > 1280:
            scale = 1280 / width
            img = cv2.resize(img, (int(width * scale), int(height * scale)))

        _, buffer = cv2.imencode('.jpg', img, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        encoded_string = base64.b64encode(buffer).decode('ascii')

        # МАГИЯ ЗДЕСЬ: добавляем format=image&stroke=5 чтобы вернуть КАРТИНКУ с жирными рамками!
        url = f"https://detect.roboflow.com/{PROJECT_NAME}/{VERSION}?api_key={ROBOFLOW_API_KEY}&format=image&stroke=5"

        response = requests.post(url, data=encoded_string, headers={"Content-Type": "application/x-www-form-urlencoded"})

        # Кодируем полученную картинку для HTML
        result_img_b64 = base64.b64encode(response.content).decode('utf-8')

        # Возвращаем красивую HTML-страницу с результатом
        return f'''
        <div style="text-align: center; font-family: sans-serif; padding: 50px; background: #f0f2f5; min-height: 100vh;">
            <div style="background: white; display: inline-block; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
                <h2>DeepFocus Detection Result</h2>
                <img src="data:image/jpeg;base64,{result_img_b64}" style="max-width: 800px; border-radius: 8px; border: 2px solid #007bff;">
                <br><br>
                <a href="/" style="padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; font-size: 16px;">Upload Another File</a>
            </div>
        </div>
        '''

    except Exception as e:
        return jsonify({'code': 500, 'message': f'Error: {str(e)}'})

if __name__ == "__main__":
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)