# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IavOmni9DqyrZeatDn19HL55wDYsTzNU
"""

from flask import Flask, request, jsonify, render_template_string
import requests
import base64

app = Flask(__name__)

# Увеличиваем лимит для видео, как ты просила (100МБ)
app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024

# Данные твоего проекта
ROBOFLOW_API_KEY = "zipFoxXwSowFhMRI79Sv"
PROJECT_NAME = "candidates-chess"
VERSION = "2"

@app.route('/')
def home():
    # Делаем интерфейс чуть более строгим, но оставляем CSS для "красоты"
    return '''
    <style>
        body { font-family: sans-serif; text-align: center; padding-top: 50px; background: #f0f2f5; }
        .box { background: white; display: inline-block; padding: 30px; border-radius: 10px; shadow: 0 4px 6px rgba(0,0,0,0.1); }
        button { background: #007bff; color: white; border: none; padding: 10px 20px; cursor: pointer; border-radius: 5px; }
    </style>
    <div class="box">
        <h1>CogniMetrics AI: Chess Classifier</h1>
        <p>Upload a sample to detect focus state.</p>
        <form action="/classify" method="post" enctype="multipart/form-data">
            <input type="file" name="file" required><br><br>
            <button type="submit">Classify Sample</button>
        </form>
        <p style="font-size: 0.8em; color: gray;">Use '/classify' route for API access.</p>
    </div>
    '''

# Делаем маршрут /classify как у профессора
@app.route("/classify", methods=['POST'])
def classify():
    if 'file' not in request.files:
        return jsonify({'code': 400, 'message': 'No file uploaded'})

    file = request.files['file']
    image_bytes = file.read()
    encoded_string = base64.b64encode(image_bytes).decode('ascii')

    # Запрос к твоей YOLO-модели
    url = f"https://detect.roboflow.com/{PROJECT_NAME}/{VERSION}?api_key={ROBOFLOW_API_KEY}"
    response = requests.post(url, data=encoded_string, headers={"Content-Type": "application/x-www-form-urlencoded"})
    result = response.json()

    # Пытаемся достать главный класс (первое предсказание)
    try:
        top_prediction = result['predictions'][0]['class']
        confidence = round(result['predictions'][0]['confidence'] * 100, 2)
        message = f"Sample is classified as {top_prediction} (Confidence: {confidence}%)"
    except (KeyError, IndexError):
        top_prediction = "Unknown"
        message = "No objects detected in the sample."

    # Возвращаем JSON в формате профессора
    return jsonify({
        'code': 200,
        'message': message,
        'class': top_prediction,
        'raw_data': result # оставляем полные данные для демки
    })

import os
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)